export const tutorial = `# Tutorial
Welcome to the Hotstrings Joplin plugin. This plugin allows you to define as many hotstrings and hotkeys as you want. Each hotstring will, when activated, replace what you typed with a pre-defined expression of your choice. For example, you may choose to have "Sigma" replaced with "Σ", or "sob" replaced with "😭". When a hotkey is activated, the expression will simply be inserted at the cursor's position.

## Hotstrings
To define a hotstring or hotkey, write it in quotes on a new line, followed by one to three colons (depending on type), then the replacement text—also in quotes. You can use single quotes, double quotes, or backtick quotes.
* A single colon \`:\` defines a case-insensitive hotstring
* Two colons \`::\` define a case-sensitive hotstring
* Three colons \`:::\` define a hotkey.

Any amount of whitespace may appear anywhere on the line--**except between the colons**. You may optionally include an inline comment at the end of your definition, using either a Python-style \`#\`, or a Javascript-style \`//\`.

"smile" : "🙂"   # Just like this!

To activate a hotstring, just type it, surrounded by your start and end tokens. You can change these tokens on this plugin's settings page—or right here in this config note.

Your current start token is set to %startToken%, while your current end token is set to %endToken%. Once you finish typing the end token, the entire thing will transform into the output you defined. Try it out!

Try typing \`%startToken%smile%endToken%\` here:

## Hotkeys
When defining hotkeys, type each key's name as you normally would - it's pretty flexible. Put a + between each key in your hotstring. Your hotkey can contain Ctrl, Shift, and Alt in any combination (including none) - and then **must** consist of **exactly one** of any other key.  As an example, to use the hotkey Ctrl+Alt+P, you would type your left side as \`"Ctrl+Alt+P"\` - but it's pretty forgiving. For example, \`"control + aLT   +p"\` would also work. When activated, it will insert the text you enter on the right of the colons.

Note that, due to a [bug](https://discourse.joplinapp.org/t/bug-inconsistent-modifier-key-validation-renders-meta-super-unusable-in-keyboard-shortcuts-on-linux/29656) in Joplin, you cannot use the Windows/Super/Meta key, as it causes an unrecoverable crash in some situations.

Note also that the plugin does **NOT** verify that a hotkey is actually available to be used. If you define a hotkey and it's not working as expected, despite being correctly color-coded, it's likely that you've inadvertently entered a hotkey that Joplin or your operating system is already using for something else.

## Colors
For your convenience, hotstring and hotkey definitions which have been successfully parsed are color-coded (only in this note). All of the colors which can appear are detailed below:

### Green
A successfully detected case-insensitive hotstring.
':D' : '😃'  # Here's a Python-style comment
"+-" : "±"  // And a Javascript-style comment
"-+" : "-+"
\`happycat\` : "😺"
### Yellow
A valid hotstring, hotkey, or token, which has been overwritten by one with an identical left side lower down. Both of the following case-sensitive hotstrings define themselves on "ADDR", but only the one transforming into "5678 Oak Ave, Pittsburgh" will ever activate, because it appears lower in the note.
"ADDR" :: "1234 Elm St, Springfield"
### Blue
A successfully detected case-sensitive hotstring.
"ADDR" :: "5678 Oak Ave, Pittsburgh"
### Purple
A successfully detected hotkey.
'Ctrl+Alt+H' ::: '* * *' # Enter a horizontal rule
### Teal
Setting a token
'startToken' := '' # Empty
### Red
A hotkey which is formatted correctly, but has an invalid hotkey combination—or a token definition, with a left side that isn't 'startToken' or 'endToken'.
'Shift+Win+B' ::: '<br>' # Windows key not supported due to crash bug
'Ctrl+Alt+P+R+T' ::: '🎈 🥳 🎂 ✨ 🎉 🎊 🎁' # Must have exactly one non-modifier (so not Ctrl, Shift, or Alt) key present - this one has three (P, R, and T)
### No coloring
The plugin failed to parse the line as a valid hotstring or hotkey definition.
'sob' :::: '😭'   # Too many colons
'sadcat" : "😿"   # Mismatched quotes on left side

## Notes and limitations
### Limitations
* Hotkeys cannot distinguish between left and right modifier keys. There is no CTRL_L or CTRL_R - just CTRL, etc.
* Hotstring definitions (left sides) cannot contain newlines.
* Text replacements (right sides) CAN contain newlines and tabs. If you type \\n or \\t in your replacement string, it will be rendered as a literal newline or tab character, respectively. You can also just write literal tabs.
"details" : \`<details>\\n\\t<summary>Title</summary>\\n\\tBody\\n</details>\` # Try it out with this hotstring!
"hr" : "\\n* * *\\n" # Or this one!
*  When you add hotkeys, the plugin must create menu items for them - you may have seen them appear in the Tools menu. Due to limitations with the Joplin API, I don't believe I can remove old commands - so, since the plugin updates live as you make edits to this document, the Tools menu may start filling up with lots of commands. This is **temporary**, and all the extraneous commands and menus will disappear the next time Joplin is restarted.
*  Hotstrings and hotkeys only work in the markdown editor - the rich text editor is not supported.

### Notes
* Sometimes, hotstrings will end in other hotstrings - for example, if you have both of these defined:
"sadcat" : "😺"
"cat" : "🐈"
Then "sadcat" ends in "cat" - so you might wonder which will activate if you type "sadcat". The plugin will always prioritize case-sensitive hotstrings over case-insensitive hotstrings - and longer hotstrings over shorter hotstrings.
*  You can leave your start token or end token (or both!) blank if you prefer. The default setting has a blank start token, for example. This works just how you'd expect - with no start (or end) token, you don't have to type anything special at the start (or end) of your hotstring to activate it.
* This settings note doesn't "require" anything in it - you can delete this entire tutorial, and it will still recognize any hotstrings or hotkeys you type into it afterword.
* Hotstrings can not be empty - but replacements (right sides) can be, if desired.
* There are no length limits on hotstrings or their replacements. Be careful.
* **Tip**: Try making hotstrings for HTML or markdown that you use often - or that you would use more often, if it were faster to type or easier to remember. Try making hotstrings for special unicode characters (emoji, kaomoji, currency symbols, mathematical notation, greek letters, ...), or names, or addresses, or numbers, or abbreviations, or acronyms, or custom templates, or...
'"'     : '“'        # Left quote
'""'    : '”'        # Right quote
'--'    : '—'        # Em-dash
'-'     : '–'        # En-dash
'br'    : '\\n<br>\\n' # Linebreak
'jenny' : '867-5309' # Jenny's phone number
'1/2'   : '½'        # One half
\`e'\`    : 'é'        # e-acute

## Issues
Encounter any bugs? [Report them here](https://github.com/ntczkjfg/joplin-plugin-hotstrings/issues), and I'll do my best to fix them.
# End of tutorial
`;

export const prefill = `# Tokens
"startToken"       := "%startToken%"
"endToken"         := "%endToken%"

# Case-sensitive hotstrings

## Lowercase Greek
"alpha"            :: "α"
"beta"             :: "β"
"gamma"            :: "γ"
"delta"            :: "δ"
"epsilon"          :: "ε"
"zeta"             :: "ζ"
"eta"              :: "η"
"theta"            :: "θ"
"iota"             :: "ι"
"kappa"            :: "κ"
"lambda"           :: "λ"
"mu"               :: "μ"
"nu"               :: "ν"
"xi"               :: "ξ"
"omicron"          :: "ο"
"pi"               :: "π"
"rho"              :: "ρ"
"sigma"            :: "σ"
"tau"              :: "τ"
"upsilon"          :: "υ"
"phi"              :: "φ"
"chi"              :: "χ"
"psi"              :: "ψ"
"omega"            :: "ω"

## Uppercase Greek
"Alpha"            :: "Α"
"Beta"             :: "Β"
"Gamma"            :: "Γ"
"Delta"            :: "Δ"
"Epsilon"          :: "Ε"
"Zeta"             :: "Ζ"
"Eta"              :: "Η"
"Theta"            :: "Θ"
"Iota"             :: "Ι"
"Kappa"            :: "Κ"
"Lambda"           :: "Λ"
"Mu"               :: "Μ"
"Nu"               :: "Ν"
"Xi"               :: "Ξ"
"Omicron"          :: "Ο"
"Pi"               :: "Π"
"Rho"              :: "Ρ"
"Sigma"            :: "Σ"
"Tau"              :: "Τ"
"Upsilon"          :: "Υ"
"Phi"              :: "Φ"
"Chi"              :: "Χ"
"Psi"              :: "Ψ"
"Omega"            :: "Ω"

## Superscripts
"^0"               :: "⁰"
"^1"               :: "¹"
"^2"               :: "²"
"^3"               :: "³"
"^4"               :: "⁴"
"^5"               :: "⁵"
"^6"               :: "⁶"
"^7"               :: "⁷"
"^8"               :: "⁸"
"^9"               :: "⁹"

"^+"               :: "⁺"
"^-"               :: "⁻"
"^="               :: "⁼"
"^("               :: "⁽"
"^)"               :: "⁾"

"^a"               :: "ᵃ"
"^b"               :: "ᵇ"
"^c"               :: "ᶜ"
"^d"               :: "ᵈ"
"^e"               :: "ᵉ"
"^f"               :: "ᶠ"
"^g"               :: "ᵍ"
"^h"               :: "ʰ"
"^i"               :: "ⁱ"
"^j"               :: "ʲ"
"^k"               :: "ᵏ"
"^l"               :: "ˡ"
"^m"               :: "ᵐ"
"^n"               :: "ⁿ"
"^o"               :: "ᵒ"
"^p"               :: "ᵖ"
"^r"               :: "ʳ"
"^s"               :: "ˢ"
"^t"               :: "ᵗ"
"^u"               :: "ᵘ"
"^v"               :: "ᵛ"
"^w"               :: "ʷ"
"^x"               :: "ˣ"
"^y"               :: "ʸ"
"^z"               :: "ᶻ"

"^A"               :: "ᴬ"
"^B"               :: "ᴮ"
"^D"               :: "ᴰ"
"^E"               :: "ᴱ"
"^G"               :: "ᴳ"
"^H"               :: "ᴴ"
"^I"               :: "ᴵ"
"^J"               :: "ᴶ"
"^K"               :: "ᴷ"
"^L"               :: "ᴸ"
"^M"               :: "ᴹ"
"^N"               :: "ᴺ"
"^O"               :: "ᴼ"
"^P"               :: "ᴾ"
"^R"               :: "ᴿ"
"^T"               :: "ᵀ"
"^U"               :: "ᵁ"
"^V"               :: "ⱽ"
"^W"               :: "ᵂ"

## Subscripts
"_0"               :: "₀"
"_1"               :: "₁"
"_2"               :: "₂"
"_3"               :: "₃"
"_4"               :: "₄"
"_5"               :: "₅"
"_6"               :: "₆"
"_7"               :: "₇"
"_8"               :: "₈"
"_9"               :: "₉"
"_10"              :: "⏨"

"_+"               :: "₊"
"_-"               :: "₋"
"_="               :: "₌"
"_("               :: "₍"
"_)"               :: "₎"
"_""               :: "„"

"_a"               :: "ₐ"
"_e"               :: "ₑ"
"_h"               :: "ₕ"
"_i"               :: "ᵢ"
"_j"               :: "ⱼ"
"_k"               :: "ₖ"
"_l"               :: "ₗ"
"_m"               :: "ₘ"
"_n"               :: "ₙ"
"_o"               :: "ₒ"
"_p"               :: "ₚ"
"_r"               :: "ᵣ"
"_s"               :: "ₛ"
"_t"               :: "ₜ"
"_u"               :: "ᵤ"
"_v"               :: "ᵥ"
"_x"               :: "ₓ"

## Accented characters
"A'"               :: "Á"
"a'"               :: "á"
"A\`"               :: "À"
"a\`"               :: "à"
"A-"               :: "Ā"
"a-"               :: "ā"
"Av"               :: "Ǎ"
"av"               :: "ǎ"
"A^"               :: "Â"
"a^"               :: "â"
"Ao"               :: "Å"
"ao"               :: "å"
"A**"              :: "Ä"
"a**"              :: "ä"
"A~"               :: "Ã"
"a~"               :: "ã"
"A-acute"          :: "Á"
"a-acute"          :: "á"
"A-grave"          :: "À"
"a-grave"          :: "à"
"A-macron"         :: "Ā"
"a-macron"         :: "ā"
"A-caron"          :: "Ǎ"
"a-caron"          :: "ǎ"
"A-circumflex"     :: "Â"
"a-circumflex"     :: "â"
"A-ring"           :: "Å"
"a-ring"           :: "å"
"AA"               :: "Å"
"aa"               :: "å"
"A-umlaut"         :: "Ä"
"a-umlaut"         :: "ä"
"A-tilde"          :: "Ã"
"a-tilde"          :: "ã"

"E'"               :: "É"
"e'"               :: "é"
"E\`"               :: "È"
"e\`"               :: "è"
"E-"               :: "Ē"
"e-"               :: "ē"
"Ev"               :: "Ě"
"ev"               :: "ě"
"E^"               :: "Ê"
"e^"               :: "ê"
"E**"              :: "Ë"
"e**"              :: "ë"
"E-acute"          :: "É"
"e-acute"          :: "é"
"E-grave"          :: "È"
"e-grave"          :: "è"
"E-macron"         :: "Ē"
"e-macron"         :: "ē"
"E-caron"          :: "Ě"
"e-caron"          :: "ě"
"E-circumflex"     :: "Ê"
"e-circumflex"     :: "ê"
"E-umlaut"         :: "Ë"
"e-umlaut"         :: "ë"

"I'"               :: "Í"
"i'"               :: "í"
"I\`"               :: "Ì"
"i\`"               :: "ì"
"I-"               :: "Ī"
"i-"               :: "ī"
"Iv"               :: "Ǐ"
"iv"               :: "ǐ"
"I^"               :: "Î"
"i^"               :: "î"
"I**"              :: "Ï"
"i**"              :: "ï"
"I-acute"          :: "Í"
"i-acute"          :: "í"
"I-grave"          :: "Ì"
"i-grave"          :: "ì"
"I-macron"         :: "Ī"
"i-macron"         :: "ī"
"I-caron"          :: "Ǐ"
"i-caron"          :: "ǐ"
"I-circumflex"     :: "Î"
"i-circumflex"     :: "î"
"I-umlaut"         :: "Ï"
"i-umlaut"         :: "ï"

"O'"               :: "Ó"
"o'"               :: "ó"
"O\`"               :: "Ò"
"o\`"               :: "ò"
"O-"               :: "Ō"
"o-"               :: "ō"
"Ov"               :: "Ǒ"
"ov"               :: "ǒ"
"O^"               :: "Ô"
"o^"               :: "ô"
"O**"              :: "Ö"
"o**"              :: "ö"
"O/"               :: "Ø"
"o/"               :: "ø"
"O-acute"          :: "Ó"
"o-acute"          :: "ó"
"O-grave"          :: "Ò"
"o-grave"          :: "ò"
"O-macron"         :: "Ō"
"o-macron"         :: "ō"
"O-caron"          :: "Ǒ"
"o-caron"          :: "ǒ"
"O-circumflex"     :: "Ô"
"o-circumflex"     :: "ô"
"O-umlaut"         :: "Ö"
"o-umlaut"         :: "ö"
"O-slash"          :: "Ø"
"o-slash"          :: "ø"

"U'"               :: "Ú"
"u'"               :: "ú"
"U\`"               :: "Ù"
"u\`"               :: "ù"
"U-"               :: "Ū"
"u-"               :: "ū"
"Uv"               :: "Ǔ"
"uv"               :: "ǔ"
"U*'"              :: "Ǘ"
"u*'"              :: "ǘ"
"U*\`"              :: "Ǜ"
"u*\`"              :: "ǜ"
"U*-"              :: "Ǖ"
"u*-"              :: "ǖ"
"U*v"              :: "Ǚ"
"u*v"              :: "ǚ"
"U^"               :: "Û"
"u^"               :: "û"
"Uo"               :: "Ů"
"uo"               :: "ů"
"U**"              :: "Ü"
"u**"              :: "ü"
"U-acute"          :: "Ú"
"u-acute"          :: "ú"
"U-grave"          :: "Ù"
"u-grave"          :: "ù"
"U-macron"         :: "Ū"
"u-macron"         :: "ū"
"U-caron"          :: "Ǔ"
"u-caron"          :: "ǔ"
"U-circumflex"     :: "Û"
"u-circumflex"     :: "û"
"U-ring"           :: "Ů"
"u-ring"           :: "ů"
"U-umlaut"         :: "Ü"
"u-umlaut"         :: "ü"

"C,"               :: "Ç"
"c,"               :: "ç"
"C-cedilla"        :: "Ç"
"c-cedilla"        :: "ç"

"N~"               :: "Ñ"
"n~"               :: "ñ"
"N-tilde"          :: "Ñ"
"n-tilde"          :: "ñ"

"Y'"               :: "Ý"
"y'"               :: "ý"
"Y-acute"          :: "Ý"
"y-acute"          :: "ý"

"AE"               :: "Æ"
"ae"               :: "æ"
"OE"               :: "Œ"
"oe"               :: "œ"

"slong"            :: "ſ"
"Thorn"            :: "Þ"
"thorn"            :: "þ"

# Case-insensitive hotstrings

## Generic accent marks
"-'"               : "́"
"-\`"               : "̀"
"-^"               : "̂"
"-o"               : "̊" # Overridden by "-o" ⊖ operator below
"-,"               : "̧"
"-**"              : "̈"
"-~"               : "̃"
"-acute"           : "́"
"-grave"           : "̀"
"-circumflex"      : "̂"
"-ring"            : "̊"
"-cedilla"         : "̧"
"-umlaut"          : "̈"
"-tilde"           : "̃"

## Comparators
"!<"               : "≮"
"!<="              : "≰"
"<="               : "≤"
"<<"               : "≪"
"!>"               : "≯"
"!>="              : "≱"
">="               : "≥"
">>"               : "≫"
"!="               : "≠"
"!~="              : "≉"
"~="               : "≈"
"proportional"     : "∝"
"!congruent"       : "≆"
"congruent"        : "≅"
"=~"               : "≅"
"!==="             : "≢"
"==="              : "≡"

## Operators
"+-"               : "±"
"-+"               : "∓"
"composite"        : "∘"
"of"               : "∘"
"ring"             : "∘"
"cuberoot"         : "∛"
"fourthroot"       : "∜"
"root"             : "√"
"sqrt"             : "√"
"integral"         : "∫"
"del"              : "∇"
"nabla"            : "∇"
"+o"               : "⊕"
"-o"               : "⊖"
"xo"               : "⊗"
"/o"               : "⊘"
"*o"               : "⊙"
"*"                : "•"
"partial"          : "∂"
"-dot"             : "̇"
"-dotdot"          : "̈"
"lceil"            : "⌈"
"lceiling"         : "⌈"
"leftceiling"      : "⌈"
"rceil"            : "⌉"
"rceiling"         : "⌉"
"rightceiling"     : "⌉"
"lfloor"           : "⌊"
"leftfloor"        : "⌊"
"rfloor"           : "⌋"
"rightfloor"       : "⌋"
"division"         : "÷"
"divide"           : "÷"
"/"                : "⁄"
"!divides"         : "∤"
"divides"          : "∣"

## Sets
"!propersubset"    : "⊄"
"propersubset"     : "⊂"
"!subset"          : "⊈"
"subset"           : "⊆"
"!propersuperset"  : "⊅"
"propersuperset"   : "⊃"
"!superset"        : "⊉"
"superset"         : "⊇"
"!element"         : "∉"
"element"          : "∈"
"in"               : "∈"
"!exists"          : "∄"
"exists"           : "∃"
"intersect"        : "⋂"
"union"            : "⋃"
"forall"           : "∀"
"nullset"          : "∅"
"null"             : "∅"
"emptyset"         : "∅"
"empty"            : "∅"
"reals"            : "ℝ"
"rationals"        : "ℚ"
"integers"         : "ℤ"
"complex"          : "ℂ"
"naturals"         : "ℕ"
"universal"        : "𝕌"
"universe"         : "𝕌"
"powerset"         : "𝒫"

## Logic
"therefore"        : "∴"
"because"          : "∵"
"not"              : "¬"
"and"              : "⋀"
"xor"              : "⊕"
"or"               : "⋁"
"implies"          : "⇒"
"then"             : "⇒"
"iff"              : "⇔"
"ifandonlyif"      : "⇔"

## Arrows
"upleft"           : "↖"
"leftup"           : "↖"
"upright"          : "↗"
"rightup"          : "↗"
"downright"        : "↘"
"rightdown"        : "↘"
"downleft"         : "↙"
"leftdown"         : "↙"
"<->"              : "↔"
"leftright"        : "↔"
"rightleft"        : "↔"
"horizontal"       : "↔"
"<-"               : "←"
"left"             : "←"
"->"               : "→"
"right"            : "→"
"up"               : "↑"
"down"             : "↓"
"updown"           : "↕"
"downup"           : "↕"
"vertical"         : "↕"
"<=="              : "⇐"
"==>"              : "⇒"
"<=>"              : "⇔"

## Units
"micro"            : "μ"
" degrees"         : "°"
"degrees"          : "°"
" degree"          : "°"
"degree"           : "°"
"deg"              : "°"
"degreesC"         : "℃"
"degreeC"          : "℃"
"degC"             : "℃"
"degreesF"         : "℉"
"degreeF"          : "℉"
"degF"             : "℉"
"ohm"              : "Ω"

## Astronomical
"sol"              : "☉"

"mercury"          : "☿"
"venus"            : "♀"
"earth"            : "⨁"
"earth2"           : "♁"
"luna"             : "☾"
"mars"             : "♂"
"jupiter"          : "♃"
"saturn"           : "♄"
"uranus"           : "⛢"
"uranus2"          : "♅"
"neptune"          : "♆"
"pluto"            : "♇"
"pluto2"           : "⯓"

"aries"            : "♈"
"taurus"           : "♉"
"gemini"           : "♊"
"cancer"           : "♋"
"leo"              : "♌"
"virgo"            : "♍"
"libra"            : "♎"
"scorpius"         : "♏"
"sagittarius"      : "♐"
"capricorn"        : "♑"
"aquarius"         : "♒"
"pisces"           : "♓"
"ophiuchus"        : "⛎"

"ceres"            : "⚳"

## Currency
"usd"              : "$"
"cent"             : "¢"
"cents"            : "¢"
"gbp"              : "£"
"currency"         : "¤"
"scarab"           : "¤"
"yen"              : "¥"
"euro"             : "€"
"btc"              : "₿"
"$p"               : "₽"

## Specific numbers
"1/"               : "⅟"
"1/2"              : "½"
"1/3"              : "⅓"
"2/3"              : "⅔"
"1/4"              : "¼"
"3/4"              : "¾"
"1/5"              : "⅕"
"2/5"              : "⅖"
"3/5"              : "⅗"
"4/5"              : "⅘"
"1/6"              : "⅙"
"5/6"              : "⅚"
"1/7"              : "⅐"
"1/8"              : "⅛"
"3/8"              : "⅜"
"5/8"              : "⅝"
"7/8"              : "⅞"
"1/9"              : "⅑"
"1/10"             : "⅒"
"infinity"         : "∞"

## Punctuation and symbols
"!!"               : "‼️"
"inverted?!"       : "⸘"
"flipped?!"        : "⸘"
"flip?!"           : "⸘"
"?!"               : "‽"
"inverted!"        : "¡"
"flipped!"         : "¡"
"flip!"            : "¡"
"inverted?"        : "¿"
"flipped?"         : "¿"
"flip?"            : "¿"
"numero"           : "№"
"No."              : "№"
"copyright"        : "©"
"trademark"        : "™"
"tm"               : "™"
"registered"       : "®"
"info"             : "ⓘ"
"information"      : "ⓘ"
"section"          : "§"
"ddagger"          : "‡"
"dagger"           : "†"
"paragraph"        : "¶"
"pilcrow"          : "¶"
"\\n"               : "\\n"
"\\t"               : "\\t"
"-"                : "–"
"--"               : "—"
""""               : "”"
"""                : "“"
"''"               : "’"
"'"                : "‘"
"qed"              : "∎"
"_..."             : "⋰"
"^..."             : "⋱"
"...."             : "⋮"
"..."              : "⋯"
".c"               : "。"
"?c"               : "？"
"!c"               : "！"
":c"               : "："
",c"               : "，"
";c"               : "；"

## Kaomoji
"_shrug"           : "¯\\_(ツ)_/¯"
"_perv"            : "( ͡° ͜ʖ ͡°)"
"_unflip"          : "┬─┬ノ( °◡° ノ)"
"_flip"            : "(╯°□°）╯︵ ┻━┻"
"_disapprove"      : "ಠ_ಠ"
"_sunglasses1"     : "( •_•)>⌐■-■"
"_sunglasses2"     : "(⌐■_■)"
"_pointright"      : "(☞ﾟヮﾟ)☞"
"_pointleft"       : "☜(ﾟヮﾟ☜)"
"_disappointed"    : "(¬_¬ )"
"_hug"             : "༼ つ ◕_◕ ༽つ"

## Miscellaneous
"bom"              : "﻿"
"female"           : "♀"
"male"             : "♂"
"trans"            : "⚧"
"perpendicular"    : "⟂"
"rightangle"       : "⦜"
"triangle"         : "△"
"angle"            : "∠"
"-bar"             : "̅"
"-overscore"       : "̅"
"-overline"        : "̅"
"-hat"             : "̂"
"aleph"            : "ℵ"
"0 "               : "​"
". "               : "⠀"
"nbsp"             : " "
"communism"        : "☭"
"hammerandsickle"  : "☭"
"censored"         : "█"
"redacted"         : "█"
"rtl"              : "‏"
"ankh"             : "☥"
"Rx"               : "℞"
"sine"             : "∿"
"bullet"           : "•"
"flat"             : "♭"
"sharp"            : "♯"
"natural"          : "♮"
"nat"              : "♮"
"diamond"          : "♦"
"glitch"           : "â€™"
"glitch2"          : "�"

# Emoji
"emoji"            : "️"
"EJC"              : "‍"

## Heads
":)"               : "🙂"
":D"               : "😃"
"=D"               : "😄"
";)"               : "😉"
"^_^"              : "😁"
"*_*"              : "🤩"
"XD"               : "😆"
"B)"               : "😎"
":|"               : "😐"
":/"               : "🫤"
">_<"              : "😖"
">.<"              : "😖"
":*"               : "😙"
":P"               : "😛"
";P"               : "😜"
">:("              : "😠"
":("               : "🙁"
">=("              : "😠"
":S"               : "🥴"
":')"              : "🥲"
":'("              : "😢"
":x"               : "😬"
"xp"               : "😝"
":O"               : "😮"
"unsure"           : "😕"
"angel"            : "😇"
"devil"            : "😈"
"wink"             : "😉"
"blush"            : "😊"
"inlove"           : "🥰"
"love"             : "😍"
"love2"            : "🥰"
"smirk"            : "😏"
"smug"             : "😏"
"stoic"            : "😐"
"kiss"             : "😙"
"kiss2"            : "😘"
"tongue"           : "😛"
"mad"              : "😤"
"angry"            : "😠"
"bull"             : "😤"
"exhale"           : "😤"
"nervous"          : "😟"
"anxious"          : "😨"
"scared"           : "😨"
"worried"          : "😰"
"relieved"         : "😌"
"sleepy"           : "😪"
"sob"              : "😭"
"shocked"          : "😳"
"flush"            : "😳"
"flushed"          : "😳"
"embarrassed"      : "😳"
"surprised"        : "😲"
"scream"           : "😱"
"astonished"       : "😲"
"monocle"          : "🧐"
"sleep"            : "😴"
"sleeping"         : "😴"
"dizzy"            : "😵‍💫"
"nomouth"          : "😶"
"mask"             : "😷"
"upsidedown"       : "🙃"
"rolleyes"         : "🙄"
"zipper"           : "🤐"
"greed"            : "🤑"
"greedy"           : "🤑"
"sick"             : "🤒"
"nerd"             : "🤓"
"thinking"         : "🤔"
"injured"          : "🤕"
"hug"              : "🤗"
"cold"             : "🥶"
"nauseous"         : "🤢"
"disgust"          : "🤢"
"laugh"            : "🤣"
"drool"            : "🤤"
"sneeze"           : "🤧"
"eyebrow"          : "🤨"
"crazy"            : "🤪"
"shh"              : "🤫"
"giggle"           : "🤭"
"puke"             : "🤮"
"vomit"            : "🤮"
"mindblown"        : "🤯"
"yawn"             : "🥱"
"party"            : "🥳"
"party2"           : "🎈 🥳 🎂 ✨ 🎉 🎊 🎁"
"peek"             : "🫣"
"brushingteeth"    : "😁😆😩😲😬"
"please"           : "🥺"
"beg"              : "🥺👉👈"
"plead"            : "🥺"
"cute"             : "🥹"
"happytears"       : "🥹"
"melting"          : "🫠"
"salute"           : "🫡"
"o7"               : "🫡"
"yum"              : "🤤"
"tasty"            : "😋"
"hot"              : "🥵"
"sweat"            : "🥵"
"spicy"            : "🥵"
"relief"           : "😅"
"phew"             : "😅"
":'D"              : "😅"
"baby"             : "👶"
"liar"             : "🤥"
"lying"            : "🤥"
"santa"            : "🎅"
"santaclaus"       : "🎅"
"mrsclaus"         : "🤶"
"fuck"             : "🤬"
"weary"            : "😩"
"pensive"          : "😔"
"cowboy"           : "🤠"
"proud"            : "️☺"
"skull"            : "💀"
"dead"             : "💀"
"alien"            : "👽"
"robot"            : "🤖"
"clown"            : "🤡"
"sigh"             : "😮‍💨"
"moonface"         : "🌚"
"dottedface"       : "🫥"
"dotted"           : "🫥"
"dashed"           : "🫥"
"dashedface"       : "🫥"

## Poses
"hugging"          : "🫂"
"facepalm"         : "🤦"
"shrug"            : "🤷"
"wave"             : "🙋"
"full"             : "🫄"
"hair"             : "💁"
"bike"             : "🚴"
"wizard"           : "🧙"
"vampire"          : "🧛"
"dracula"          : "🧛"
"ghost"            : "👻"
"snowman"          : "⛄"

## Body parts
"lips"             : "💋"
"bitelip"          : "🫦"
"mouth"            : "👄"
"eyes"             : "👀"
"brain"            : "🧠"
"dna"              : "🧬"
"pray"             : "🙏"
"eye"              : "👁️"
"ear"              : "👂"
"nose"             : "👃"
"blood"            : "🩸"
"luck"             : "🤞"
"pinch"            : "🤏"
"small"            : "🤏"
"tiny"             : "🤏"
"horns"            : "🤘"
"callme"           : "🤙"
"chur"             : "🤙"
"handshake"        : "🤝"
"deal"             : "🤝"
"pointup"          : "👆"
"pointdown"        : "👇"
"pointleft"        : "👈"
"pointright"       : "👉"
"point"            : "👉"
"fist"             : "👊"
"ok"               : "👌"
"thumbsup"         : "👍"
"thumbsdown"       : "👎"
"rock"             : "👊"
"paper"            : "✋"
"scissors"         : "✌️"
"spock"            : "🖖"
"clap"             : "👏"
"fuckyou"          : "🖕"
"LLAP"             : "🖖"
"hand"             : "✋"
"v"                : "✌️"
"money"            : "🤌"
"strong"           : "💪"
"muscle"           : "💪"

## Hearts
"heartsuit"        : "♥️"
"<3"               : "❤️"
"</3"              : "💔"
"brokenheart"      : "💔"
"orangeheart"      : "🧡"
"whiteheart"       : "🤍"
"brownheart"       : "🤎"
"blackheart"       : "🖤"
"redheart"         : "❤️"
"lightblueheart"   : "🩵"
"blueheart"        : "💙"
"greenheart"       : "💚"
"yellowheart"      : "💛"
"goldheart"        : "💛"
"goldenheart"      : "💛"
"purpleheart"      : "💜"
"pinkheart"        : "🩷"
"greyheart"        : "🩶"
"grayheart"        : "🩶"
"twohearts"        : "💕"
"realheart"        : "🫀"
"anatomicalheart"  : "🫀"
"flamingheart"     : "❤️‍🔥"
"burningheart"     : "❤️‍🔥"
"bleedingheart"    : "❣️"
"<3!"              : "❣️"
"handheart"        : "🫶"
"handsheart"       : "🫶"
"plainheart"       : "♡"
"textheart"        : "♡"
"heartbeat"        : "💓"
"beatingheart"     : "💓"
"heart"            : "❤️"

## Animals and plants
"happycat"         : "😺"
"laughcat"         : "😹"
"lolcat"           : "😹"
"smilecat"         : "😸"
"lovecat"          : "😻"
"smirkcat"         : "😼"
"kisscat"          : "😽"
"madcat"           : "😾"
"angrycat"         : "😾"
"sobcat"           : "😿"
"crycat"           : "😿"
"sadcat"           : "😿"
"screamcat"        : "🙀"
"cat"              : "🐈"
"seenoevil"        : "🙈"
"hearnoevil"       : "🙉"
"speaknoevil"      : "🙊"
"alligator"        : "🐊"
"crocodile"        : "🐊"
"croc"             : "🐊"
"snake"            : "🐍"
"tss"              : "🐍"
"bee"              : "🐝"
"bat"              : "🦇"
"lizard"           : "🦎"
"spider"           : "🕷️"
"palmtree"         : "🌴"
"christmastree"    : "🎄"
"tree"             : "🌳"
"cactus"           : "🌵"
"clover"           : "🍀"
"mushroom"         : "🍄"
"pumpkin"          : "🎃"
"jack-o-lantern"   : "🎃"
"jackolantern"     : "🎃"

## Food
"taco"             : "🌮"
"eggplant"         : "🍆"
"peach"            : "🍑"
"watermelon"       : "🍉"
"banana"           : "🍌"
"pineapple"        : "🍍"
"apple"            : "🍎"
"pizza"            : "🍕"
"donut"            : "🍩"
"cookie"           : "🍪"
"pickle"           : "🥒"
"egg"              : "🥚"
"broccoli"         : "🥦"
"sandwich"         : "🥪"
"cheese"           : "🧀"
"chocolate"        : "🍫"
"candy"            : "🍬"
"lollipop"         : "🍭"
"bottle"           : "🍼"
"milk"             : "🍼"
"popcorn"          : "🍿"
"cake"             : "🎂"

## Nature
"storm"            : "⛈️"
"zap"              : "⚡"
"lightning"        : "⚡"
"bolt"             : "⚡"
"snow"             : "❄️"
"snowflake"        : "❄️"
"star"             : "⭐"
"rainbow"          : "🌈"
"globe1"           : "🌍"
"globe"            : "🌎"
"globe2"           : "🌎"
"globe3"           : "🌏"
"moon1"            : "🌑"
"moon2"            : "🌒"
"moon3"            : "🌓"
"moon4"            : "🌔"
"moon5"            : "🌕"
"moon6"            : "🌖"
"moon7"            : "🌗"
"moon8"            : "🌘"
"moon"             : "🌙"
"sun"              : "🌞"
"raincloud"        : "🌧️"
"fire"             : "🔥"
"water"            : "💦"
"wet"              : "💦"

## Objects
"pin"              : "📌"
"crown"            : "👑"
"puzzle"           : "🧩"
"alarm"            : "🚨"
"alert"            : "🚨"
"siren"            : "🚨"
"piano"            : "🎹"
"key"              : "🔑"
"lock"             : "🔒"
"bell"             : "🔔"
"knife"            : "🔪"
"gun"              : "🔫"
"web"              : "🕸️"
"sword"            : "🗡️"
"rocket"           : "🚀"
"bed"              : "🛌"
"drum"             : "🥁"
"badum"            : "🥁"
"sunglasses"       : "🕶"
"glasses"          : "👓"
"safetypin"        : "🧷"
"jab"              : "💉"
"hourglass"        : "⏳"
"hourglass2"       : "⌛"
"umbrella"         : "☂️"
"pickaxe"          : "⛏️"
"airplane"         : "✈️"
"plane"            : "✈️"
"gift"             : "🎁"
"present"          : "🎁"
"balloon"          : "🎈"
"diamond2"         : "💎"
"bomb"             : "💣"
"poop"             : "💩"
"watch"            : "⌚"
"swords"           : "⚔️"
"fireworks"        : "🎆"
"sparkler"         : "🎇"
"popper"           : "🎉"
"confetti"         : "🎊"
"target"           : "🎯"
"pirateflag"       : "🏴‍☠️"
"flag2"            : "🚩"
"jollyroger"       : "🏴‍☠️"
"money2"           : "💰"

## Symbols
"caution"          : "⚠️"
"warning"          : "⚠️"
"underage"         : "🔞"
"18+"              : "🔞"
"anger"            : "💢"
"100"              : "💯"
"radioactive"      : "☢️"
"biohazard"        : "☣️"
"islam"            : "☪️"
"muslim"           : "☪️"
"spade"            : "♠️"
"club"             : "♣️"
"diamondsuit"      : "♦️"
"recycle"          : "♻️"
"check"            : "✅"
"check2"           : "✔️"
"checkmark"        : "✔️"
"cross"            : "✝️"
"christian"        : "✝️"
"jewish"           : "✡️"
"starofdavid"      : "✡️"
"menorah"          : "🕎"
"x"                : "❌"
"zzz"              : "💤"
"shootingstar"     : "💫"
"dizzy2"           : "💫"
"no"               : "🚫"
"cancel"           : "🚫"
"prohibited"       : "🚫"
"graphup"          : "📈"
"graphdown"        : "📉"
"fart"             : "💨"
"red"              : "🟥"
"orange"           : "🟧"
"yellow"           : "🟨"
"green"            : "🟩"
"blue"             : "🟦"
"purple"           : "🟪"
"brown"            : "🟫"
"black"            : "⬛"
"white"            : "⬜"
"red2"             : "🔴"
"orange2"          : "🟠"
"yellow2"          : "🟡"
"green2"           : "🟢"
"blue2"            : "🔵"
"purple2"          : "🟣"
"brown2"           : "🟤"
"black2"           : "⚫"
"white2"           : "⚪"
"sound"            : "🔊"
"audio"            : "🔊"
"mute"             : "🔈"
"muted"            : "🔈"
"sparkles"         : "✨"
"shiny"            : "✨"
"music"            : "🎵"
"plainnote"        : "♪"
"textnote"         : "♪"
"note"             : "🎵"
"plainstar"        : "★"
"textstar"         : "★"
"hollowstar"       : "☆"
"crossbones"       : "☠️"
"!?"               : "⁉️"
"!"                : "❗"
"?"                : "❓"
`;
